//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaLocalDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalDatabaseEntities : DbContext
    {
        public LocalDatabaseEntities()
            : base("name=LocalDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestCycle> TestCycles { get; set; }
        public virtual DbSet<TestCycleStatu> TestCycleStatus { get; set; }
        public virtual DbSet<WorkFlow> WorkFlows { get; set; }
        public virtual DbSet<WorkFlowExecutionLog> WorkFlowExecutionLogs { get; set; }
        public virtual DbSet<WorkFlowExecutionStatu> WorkFlowExecutionStatus { get; set; }
        public virtual DbSet<WorkFlowTestStepMapping> WorkFlowTestStepMappings { get; set; }
    }
}
