//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaLocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowTestStepMapping
    {
        public long Id { get; set; }
        public long WorkFlowId { get; set; }
        public string TestStepName { get; set; }
        public int ExecutionSequence { get; set; }
    
        public virtual WorkFlow WorkFlow { get; set; }
    }
}
