//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaLocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkFlowExecutionLog
    {
        public long Id { get; set; }
        public long WorkFlowId { get; set; }
        public string TesterName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public long StatusId { get; set; }
        public string ReportPath { get; set; }
    
        public virtual WorkFlowExecutionStatu WorkFlowExecutionStatu { get; set; }
    }
}
